name: CI
on: [push, pull_request]
jobs:
  pre_job:
    name: Check duplicate
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
          concurrent_skipping: same_content
          do_not_skip: '["pull_request", "schedule", "workflow_dispatch"]'

  build:
    name: Test
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install

      - name: Dynamics tests
        run: pipenv run python ./tests/test_gen_dynamics.py

      - name: Harmonium tests
        run: pipenv run python ./tests/test_harmonium.py

      - name: Identity tests
        run: pipenv run python ./tests/test_identity.py
